### ISSUE TITLE
When will btmscan be finished?

### ISSUE THREAD

**Issue by NorthFoxz** [Bytom/btmscan#1]
Hi,
When will btmscan be finished?

**Comment by NorthFoxz** [comment]
I've made a prototype of bytomscan by this repository,
if you are interested,
help me improve it, thanks!
https://bytomscan.io/

**Comment by wliyongfeng** [comment]
Maybe end of this week, a beta version will be online.  
Currently we have no time to support your personal project. Ask questions under this project if you need any help.
